from enum import Enum


class TokenType(Enum):
    IDENTIFIER = "IDENTIFICADOR"
    NUMBER = "NUMERO"
    STRING = "CADENA"
    CHAR_LITERAL = "CARACTER"

    INT = "INT"
    FLOAT = "FLOAT"
    CHAR = "CHAR"
    VOID = "VOID"

    IF = "IF"
    ELSE = "ELSE"
    WHILE = "WHILE"
    RETURN = "RETURN"
    FOR = "FOR"

    PLUS = "SUMA"
    MINUS = "RESTA"
    MULTIPLY = "MULTIPLICACION"
    DIVIDE = "DIVISION"
    MODULO = "MODULO"

    ASSIGN = "ASIGNACION"

    EQUAL = "IGUAL"
    NOT_EQUAL = "NO_IGUAL"
    LESS_THAN = "MENOR_QUE"
    GREATER_THAN = "MAYOR_QUE"
    LESS_EQUAL = "MENOR_IGUAL"
    GREATER_EQUAL = "MAYOR_IGUAL"

    AND = "AND"
    OR = "OR"
    NOT = "NOT"

    LPAREN = "PARENTESIS_IZQ"
    RPAREN = "PARENTESIS_DER"
    LBRACE = "LLAVE_IZQ"
    RBRACE = "LLAVE_DER"
    COMMA = "COMA"
    SEMICOLON = "PUNTO_Y_COMA"

    COMMENT = "COMENTARIO"
    PREPROCESSOR = "PREPROCESADOR"
    WHITESPACE = "ESPACIO"
    NEWLINE = "NUEVA_LINEA"
    UNKNOWN = "DESCONOCIDO"
    EOF = "EOF"